// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpsvcmozrxfmfelnotyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhwc3ZjbW96cnhmbWZlbG5vdHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTQ4ODcsImV4cCI6MjA2NTY5MDg4N30.gjSh2_PCF4AX_GGwgI-Fb-U5AqATlL5dANV-Kf_h-xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);